FROM python:3.10

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install flask
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN apt update && apt install ffmpeg -y
RUN pip install -U openai-whisper
#RUN python -c "import whisper"
RUN python -c "import whisper;modelname = 'medium';model = whisper.load_model(modelname)"


COPY . .

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
